module.exports = [
    {
        men: [
            // "T-Shirts men",
            "Kurta men",
            "Vest men",
            "Polo T-Shirts men",
            "V-Neck T-Shirts men",
            "Henley T-Shirts men",
            "Color Block T-Shirts men",
            "Hoodies men",
            "Sweatshirt men",
            "Jackets men",
            "Denims men",
            "Shorts men",
            "Joggers men",
            "Pyjamas men",
            "Boxers men",
            "Protective Masks men",
            "Multipurpose Sanitizers men",
            "Protective Eyewear men",
            "Essentials Combo Kits men",
            "Hand Wash men",
            "Face Shield men",
            "PPE Kit men",
            "Thermometer men",
            "Shoe Covers men",
            "Hand Sanitizers men",
            "Mobile Accessories men",
            "Mobile Covers men",
            "Laptop Bags men",
            "Small Backpacks men",
            "Notebooks men",
            "Designer Wall Frames men",
            "Flip Flops men",
            "Sliders men",
            "Socks men"
        ],
        women: [
            "T-Shirts women",
            "Fashion Tops women",
            "V-Neck T-Shirts women",
            "Crop Tops women",
            "Dresses women",
            "Jackets women",
            "Hoodies women",
            "Sweatshirt women",
            "Sunactive T-Shirts women",
            "Protective Masks women",
            "Multipurpose Sanitizers women",
            "Protective Eyewear women",
            "Essentials Combo Kits women",
            "Hand Wash women",
            "Face Shield women",
            "PPE Kit women",
            "Thermometer women",
            "Shoe Covers women",
            "Hand Sanitizers women",
            "Palazzos",
            "Leggings women",
            "Denims women",
            "Joggers women",
            "Pyjamas women",
            "Boxers women",
            "Mobile Accessories women",
            "Mobile Covers women",
            "Laptop Bags women",
            "Small Backpacks women",
            "Notebooks women",
            "Designer Wall Frames women",
            "Flip Flops women",
            "Sliders women",
            "Socks women"
        ],
    }
]